apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-attendance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-attendance
  template:
    metadata:
      labels:
        app: student-attendance
    spec:
      containers:
        - name: student-attendance
          image: student-attendance
          imagePullPolicy: Never
          ports:
            - containerPort: 80

